Repository novalumo/disaster-prevention-info, pull requests merged in 2025-03, with the labels that each got.

#19 OSSプロジェクトとしてのドキュメントとテンプレートを整備
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/service_request.yml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: dev: 改善

#24 [機能] PWA 対応 on Next.js
  src/app/manifest.ts
  tailwind.config.ts
Labels: dev: 改善

#26 feat: Enhance PWA and mobile viewport configuration
  src/app/layout.tsx
  src/app/ofunato/components/OfunatoBottomNav.tsx
Labels: dev: 改善

#28 feat: Add Kizuna Project Sanriku for donation
  src/app/ofunato/support/DonationInfoCard.tsx
Labels: ボランティア

#30 タブのスクロール対応と宿泊施設情報の追加
  src/app/ofunato/data/services.ts
  src/app/ofunato/services/ServicesCard.tsx
  src/lib/time.ts
Labels: 宿泊

#33 碁石海岸キャンプ場のシャワー施設を追加
  src/app/ofunato/data/services.ts
Labels: 入浴施設

#41 feat: スター市場食堂の情報を追加
  src/app/ofunato/data/services.ts
  src/lib/time.ts
Labels: 飲食

#46 feat: 避難者向け学習施設情報を追加
  src/app/ofunato/data/services.ts
  src/app/ofunato/services/ServicesCard.tsx
  src/lib/time.ts
Labels: 学習施設

#55 複数の支援施設を追加（図書館、シャワー室、宿泊施設）
  src/app/ofunato/data/services.ts
  src/lib/time.ts
Labels: 入浴施設, 学習施設

#56 Add Yumechan NPO donation option to DonationInfoCard
  src/app/ofunato/support/DonationInfoCard.tsx
Labels: 募金

#58 ボランティアセンター予備登録導線追加
  .husky/pre-commit
  biome.jsonc
  env.d.ts
  eslint.config.mjs
  next.config.ts
  package.json
  src/app/ofunato/data/services.ts
  src/app/ofunato/support/DonationInfoCard.tsx
  src/app/ofunato/support/VolunteerInfoCard.tsx
  src/lib/time.ts
  test/setup.ts
  vitest.config.ts
Labels: ボランティア

#64 feat: 銀座ウエストの災害義援金情報を追加
  src/app/ofunato/support/DonationInfoCard.tsx
Labels: 募金

#66 Add: 壱番亭
  src/app/ofunato/data/services.ts
Labels: 飲食
